#!/usr/bin/env python3
"""Claude Code セッション横断検索.

~/.claude/projects/**/*.jsonl を全 working directory 横断で grep し、
マッチした発話の cwd / gitBranch / timestamp / sessionId / preview を出す。
「あの話したのはどこの worktree だったっけ」を解決するための CLI。

使い方は zsh 関数 `clog` (home/.zshrc.d/clog.zsh) 経由が標準。
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

PROJECTS_DIR = Path(os.environ.get("CLAUDE_PROJECTS_DIR", str(Path.home() / ".claude" / "projects")))

# 検索対象から外す prefix（コマンドエコー / system-reminder 注入を除外）
SKIP_PREFIXES = (
    "<command-",
    "<local-command",
    "<system-reminder",
    "<bash-stdout",
    "<bash-stderr",
    "Caveat: The messages below were generated by the user while running local commands",
)


@dataclass
class Hit:
    cwd: str
    branch: str
    ts: str
    role: str
    sid: str
    file: str
    lineno: int
    text: str


def parse_since(s: str) -> datetime:
    """7d / 12h / 30m / 2026-05-01 のいずれかを UTC datetime に変換."""
    m = re.fullmatch(r"(\d+)([dhmw])", s)
    if m:
        n = int(m.group(1))
        unit = m.group(2)
        delta = {
            "m": timedelta(minutes=n),
            "h": timedelta(hours=n),
            "d": timedelta(days=n),
            "w": timedelta(weeks=n),
        }[unit]
        return datetime.now(timezone.utc) - delta
    # ISO 日付（2026-05-01 等）
    return datetime.fromisoformat(s).replace(tzinfo=timezone.utc)


def extract_text(msg) -> str:
    """message.content から text part だけを連結して返す."""
    if not isinstance(msg, dict):
        return ""
    c = msg.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        parts = []
        for p in c:
            if isinstance(p, dict) and p.get("type") == "text":
                parts.append(p.get("text", ""))
        return "\n".join(parts)
    return ""


def build_matcher(queries: list[str], regex: bool, case_sensitive: bool):
    if regex:
        flags = 0 if case_sensitive else re.IGNORECASE
        patterns = [re.compile(q, flags) for q in queries]
        return lambda text: all(p.search(text) for p in patterns)
    if case_sensitive:
        return lambda text: all(q in text for q in queries)
    qs = [q.lower() for q in queries]
    return lambda text: all(q in text.lower() for q in qs)


def iter_jsonl(root: Path):
    yield from root.rglob("*.jsonl")


def parse_args():
    ap = argparse.ArgumentParser(
        description="Claude Code セッションを working directory 横断で grep",
    )
    ap.add_argument("query", nargs="+", help="検索文字列 (複数指定で AND)")
    ap.add_argument("--regex", action="store_true", help="クエリを正規表現として扱う")
    ap.add_argument(
        "-s",
        "--case-sensitive",
        action="store_true",
        help="大文字小文字を区別する (既定は ignore-case)",
    )
    ap.add_argument("--cwd", help="cwd 部分一致フィルタ (例: ebookjapan-ios)")
    ap.add_argument(
        "--since",
        help="絞り込み: 7d / 12h / 30m / 2w / 2026-05-01",
    )
    ap.add_argument(
        "--role",
        choices=["user", "assistant", "both"],
        default="both",
        help="どちらの発話を見るか (既定: both)",
    )
    ap.add_argument(
        "-g",
        "--group",
        action="store_true",
        help="cwd ごとのマッチ件数だけ表示 (どこで話したかを一覧したい時)",
    )
    ap.add_argument(
        "-n",
        "--max",
        type=int,
        default=50,
        help="最大表示件数 (既定: 50, 0 で無制限)",
    )
    ap.add_argument(
        "--full",
        action="store_true",
        help="preview を切り詰めない",
    )
    return ap.parse_args()


def main() -> int:
    args = parse_args()
    if not PROJECTS_DIR.is_dir():
        print(f"projects dir not found: {PROJECTS_DIR}", file=sys.stderr)
        return 2

    match = build_matcher(args.query, args.regex, args.case_sensitive)
    since = parse_since(args.since) if args.since else None
    role_filter = args.role

    hits: list[Hit] = []
    counts: dict[str, int] = {}

    for jsonl in iter_jsonl(PROJECTS_DIR):
        try:
            with jsonl.open(encoding="utf-8", errors="replace") as f:
                for lineno, line in enumerate(f, 1):
                    if not line.strip():
                        continue
                    try:
                        d = json.loads(line)
                    except json.JSONDecodeError:
                        continue
                    t = d.get("type")
                    if t not in ("user", "assistant"):
                        continue
                    if d.get("toolUseResult") is not None:
                        continue
                    if d.get("isMeta"):
                        continue
                    msg = d.get("message")
                    role = msg.get("role", "") if isinstance(msg, dict) else ""
                    if role_filter != "both" and role != role_filter:
                        continue
                    text = extract_text(msg)
                    if not text:
                        continue
                    stripped = text.lstrip()
                    if stripped.startswith(SKIP_PREFIXES):
                        continue
                    if not match(text):
                        continue
                    cwd = d.get("cwd", "")
                    if args.cwd and args.cwd not in cwd:
                        continue
                    ts_str = d.get("timestamp", "")
                    if since and ts_str:
                        try:
                            ts = datetime.fromisoformat(ts_str.replace("Z", "+00:00"))
                            if ts < since:
                                continue
                        except ValueError:
                            pass
                    counts[cwd] = counts.get(cwd, 0) + 1
                    hits.append(
                        Hit(
                            cwd=cwd,
                            branch=d.get("gitBranch", "") or "",
                            ts=ts_str,
                            role=role,
                            sid=d.get("sessionId", ""),
                            file=str(jsonl),
                            lineno=lineno,
                            text=text,
                        )
                    )
        except (OSError, UnicodeDecodeError):
            continue

    if args.group:
        if not counts:
            print("# 0 matches", file=sys.stderr)
            return 1
        print(f"# {sum(counts.values())} matches across {len(counts)} cwds", file=sys.stderr)
        for cwd, c in sorted(counts.items(), key=lambda x: -x[1]):
            print(f"{c:5}  {cwd}")
        return 0

    if not hits:
        print("# 0 matches", file=sys.stderr)
        return 1

    hits.sort(key=lambda h: h.ts)
    total = len(hits)
    if args.max > 0 and total > args.max:
        print(f"# {total} matches (showing last {args.max}, oldest first)", file=sys.stderr)
        hits = hits[-args.max :]
    else:
        print(f"# {total} matches", file=sys.stderr)

    for h in hits:
        preview = " ".join(h.text.split())
        if not args.full and len(preview) > 200:
            preview = preview[:200] + "…"
        ts = h.ts[:19] if h.ts else ""
        branch = f" ({h.branch})" if h.branch else ""
        print(f"{ts}  [{h.role:9}]  {h.cwd}{branch}")
        print(f"    {preview}")
        print(f"    -> {h.file}:{h.lineno}  session={h.sid}")
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
