-- Hammerspoon Configuration

-- ─────────────────────────────────────────────────────────────
-- 外部から Hammerspoon を制御するためのブリッジを有効化
-- ─────────────────────────────────────────────────────────────
-- - hs.ipc.cliInstall(): `hs -c "lua expr"` CLI ヘルパを使えるようにする
-- - hs.allowAppleScript: osascript 経由 (`tell application "Hammerspoon"
--   to execute lua code "..."`) で reload を発火できるようにする
-- どちらも初回 reload 後から有効になる。castle のメンテナンス時に
-- ターミナル側から Hammerspoon を操作できる経路を確保しておく。
require("hs.ipc")
if hs.ipc and hs.ipc.cliInstall then hs.ipc.cliInstall() end
hs.allowAppleScript(true)

-- Ctrl+SpaceでGhosttyにフォーカス（なければ起動）
local ghosttyBundleID = "com.mitchellh.ghostty"

hs.hotkey.bind({"ctrl"}, "space", function()
    local app = hs.application.get(ghosttyBundleID)
    if app then
        app:activate()
    else
        hs.application.launchOrFocusByBundleID(ghosttyBundleID)
    end
end)

-- ─────────────────────────────────────────────────────────────
-- Ghostty font-size を OS appearance に追従させる
-- ─────────────────────────────────────────────────────────────
-- castle のテーマ運用ルール「Light vs Dark = 1pt 差」を Ghostty で実現する。
-- Ghostty の theme file は font-size を silently ignore するため、本体
-- config の末尾で `config-file = ?config.local` として optional include
-- された machine-local ファイルを Hammerspoon が動的に書き換える方式を取る。
--
-- 動作:
--   1. AppleInterfaceThemeChangedNotification を distributedNotifications
--      で購読し、appearance 切替時に発火
--   2. defaults read で現在の interface style を判定 (Light / Dark)
--   3. ~/.config/ghostty/config.local を `font-size = 13` or `font-size = 14`
--      だけ書いた最小ファイルとして上書き
--   4. Ghostty メニュー → Reload Configuration を hs.application 経由で
--      自動発火 (Ghostty 起動中のみ best-effort)。Ghostty は reload で
--      color / palette / font-size を含む全設定を **既存ウィンドウにも
--      即時反映** する (実機確認済み、2026-05)
--   5. Hammerspoon 起動時にも 1 度同期 (cold start で正しい値に揃える)
--
-- 必須条件: Hammerspoon に Accessibility 権限が無いと selectMenuItem が
-- silently fail する。System Settings → Privacy & Security → Accessibility
-- で Hammerspoon を許可する必要がある。

local FONT_SIZE_LIGHT = 13
local FONT_SIZE_DARK = 14
local GHOSTTY_LOCAL_CONFIG = os.getenv("HOME") .. "/.config/ghostty/config.local"

-- defaults read -g AppleInterfaceStyle は Light モードでは "key not found"
-- エラー終了するため stderr を捨て、出力に "Dark" が含まれるかで判定する。
local function currentInterfaceStyle()
    local output = hs.execute("defaults read -g AppleInterfaceStyle 2>/dev/null", true)
    if output and output:match("Dark") then
        return "Dark"
    end
    return "Light"
end

-- Ghostty のメニューバー "Ghostty > Reload Configuration" を click する。
-- selectMenuItem は Ghostty を frontmost にせず実行できるため UX のちらつきが無い。
-- exact match を優先、念のため pattern fallback も用意 (Ghostty バージョン
-- 違い等で menu 名がずれた場合のための保険)。
local function reloadGhosttyConfig()
    local app = hs.application.get(ghosttyBundleID)
    if not app then return end
    if app:selectMenuItem({"Ghostty", "Reload Configuration"}) then return end
    app:selectMenuItem({"Ghostty", "Reload Config"}, true)
end

local function syncGhosttyFontSize()
    local style = currentInterfaceStyle()
    local size = (style == "Dark") and FONT_SIZE_DARK or FONT_SIZE_LIGHT
    local f = io.open(GHOSTTY_LOCAL_CONFIG, "w")
    if not f then return end
    f:write("# auto-generated by hammerspoon/init.lua — do not edit manually\n")
    f:write(string.format("font-size = %d\n", size))
    f:close()
    reloadGhosttyConfig()
end

-- Hammerspoon 起動 (= cold start / hs.reload()) 時に 1 度同期
syncGhosttyFontSize()

-- macOS の appearance 変更通知を購読。グローバル変数に保持して GC で
-- watcher が破棄されないようにする (Hammerspoon の watcher 共通の罠)。
ghosttyAppearanceWatcher = hs.distributednotifications.new(function()
    syncGhosttyFontSize()
end, "AppleInterfaceThemeChangedNotification")
ghosttyAppearanceWatcher:start()
