-- Hammerspoon Configuration

-- ─────────────────────────────────────────────────────────────
-- 外部から Hammerspoon を制御するためのブリッジを有効化
-- ─────────────────────────────────────────────────────────────
-- - hs.ipc.cliInstall(): `hs -c "lua expr"` CLI ヘルパを使えるようにする
-- - hs.allowAppleScript: osascript 経由 (`tell application "Hammerspoon"
--   to execute lua code "..."`) で reload を発火できるようにする
-- どちらも初回 reload 後から有効になる。castle のメンテナンス時に
-- ターミナル側から Hammerspoon を操作できる経路を確保しておく。
require("hs.ipc")
if hs.ipc and hs.ipc.cliInstall then hs.ipc.cliInstall() end
hs.allowAppleScript(true)

-- Ctrl+SpaceでGhosttyにフォーカス（なければ起動）
local ghosttyBundleID = "com.mitchellh.ghostty"

hs.hotkey.bind({"ctrl"}, "space", function()
    local app = hs.application.get(ghosttyBundleID)
    if app then
        app:activate()
    else
        hs.application.launchOrFocusByBundleID(ghosttyBundleID)
    end
end)

-- ─────────────────────────────────────────────────────────────
-- Ghostty font-size を OS appearance に追従させる
-- ─────────────────────────────────────────────────────────────
-- castle のテーマ運用ルール「Light vs Dark = 0.5pt 差」を Ghostty で実現する。
-- Ghostty の theme file は font-size を silently ignore するため、本体
-- config の末尾で `config-file = ?config.local` として optional include
-- された machine-local ファイルを Hammerspoon が動的に書き換える方式を取る。
--
-- 動作:
--   1. AppleInterfaceThemeChangedNotification を distributedNotifications
--      で購読し、appearance 切替時に発火
--   2. defaults read で現在の interface style を判定 (Light / Dark)
--   3. ~/.config/ghostty/config.local を `font-size = 12` or `font-size = 12.5`
--      だけ書いた最小ファイルとして上書き
--   4. Ghostty メニュー → Reload Configuration を hs.application 経由で
--      自動発火 (Ghostty 起動中のみ best-effort)。Ghostty は reload で
--      color / palette / font-size を含む全設定を **既存ウィンドウにも
--      即時反映** する (実機確認済み、2026-05)
--   5. Hammerspoon 起動時にも 1 度同期 (cold start で正しい値に揃える)
--
-- 必須条件: Hammerspoon に Accessibility 権限が無いと selectMenuItem が
-- silently fail する。System Settings → Privacy & Security → Accessibility
-- で Hammerspoon を許可する必要がある。
-- 新 Mac セットアップ時に忘れがちなので、起動時に hs.accessibilityState()
-- でチェックし、不足していれば通知 + アラートで自己申告する (下記参照)。

-- 起動時に Accessibility 権限をセルフチェック。castle の新 Mac セットアップ時
-- に「homeshick link は通ったが Hammerspoon が selectMenuItem できず、Ghostty
-- の font-size 切替だけ無言で死ぬ」という事故を防ぐための safeguard。
-- 通知センターと画面中央アラートの両方を出すことで、通知を見落とすユーザー
-- にも届くようにする。
if not hs.accessibilityState() then
    hs.notify.new({
        title = "Hammerspoon: Accessibility 権限が必要",
        subTitle = "Ghostty テーマ連動 font-size が動作しません",
        informativeText = "System Settings → Privacy & Security → Accessibility で Hammerspoon を許可してください (castle の Ghostty Light/Dark 連動に必要)",
        autoWithdraw = false,
        hasActionButton = false,
    }):send()
    hs.alert.show("⚠️ Hammerspoon に Accessibility 権限を付与してください\n(System Settings → Privacy & Security)", 10)
end

local FONT_SIZE_LIGHT = 12
local FONT_SIZE_DARK = 12.5
local GHOSTTY_LOCAL_CONFIG = os.getenv("HOME") .. "/.config/ghostty/config.local"

-- defaults read -g AppleInterfaceStyle は Light モードでは "key not found"
-- エラー終了するため stderr を捨て、出力に "Dark" が含まれるかで判定する。
local function currentInterfaceStyle()
    local output = hs.execute("defaults read -g AppleInterfaceStyle 2>/dev/null", true)
    if output and output:match("Dark") then
        return "Dark"
    end
    return "Light"
end

-- Ghostty のメニューバー "Ghostty > Reload Configuration" を click する。
-- selectMenuItem は Ghostty を frontmost にせず実行できるため UX のちらつきが無い。
-- exact match を優先、念のため pattern fallback も用意 (Ghostty バージョン
-- 違い等で menu 名がずれた場合のための保険)。
local function reloadGhosttyConfig()
    local app = hs.application.get(ghosttyBundleID)
    if not app then return end
    if app:selectMenuItem({"Ghostty", "Reload Configuration"}) then return end
    app:selectMenuItem({"Ghostty", "Reload Config"}, true)
end

local function syncGhosttyFontSize()
    local style = currentInterfaceStyle()
    local size = (style == "Dark") and FONT_SIZE_DARK or FONT_SIZE_LIGHT
    local f = io.open(GHOSTTY_LOCAL_CONFIG, "w")
    if not f then return end
    f:write("# auto-generated by hammerspoon/init.lua — do not edit manually\n")
    -- %g を使うことで 13 は "13"、13.5 は "13.5" と必要桁数だけ出力される。
    -- %d は浮動小数を渡すと "bad argument" になるため Light/Dark 0.5pt 差で必須。
    f:write(string.format("font-size = %g\n", size))
    f:close()
    reloadGhosttyConfig()
end

-- Hammerspoon 起動 (= cold start / hs.reload()) 時に 1 度同期
syncGhosttyFontSize()

-- macOS の appearance 変更通知を購読。グローバル変数に保持して GC で
-- watcher が破棄されないようにする (Hammerspoon の watcher 共通の罠)。
ghosttyAppearanceWatcher = hs.distributednotifications.new(function()
    syncGhosttyFontSize()
end, "AppleInterfaceThemeChangedNotification")
ghosttyAppearanceWatcher:start()

-- ─────────────────────────────────────────────────────────────
-- 時刻ベースで OS appearance を自動切替 (Hammerspoon を source of truth に)
-- ─────────────────────────────────────────────────────────────
-- macOS の純正「自動」モードは日の出/日の入りベース固定で時刻指定不可。
-- そこで Hammerspoon 側で時刻トリガーを持ち、appearance を切り替える。
-- 切替後は AppleInterfaceThemeChangedNotification が飛び、上記の
-- syncGhosttyFontSize() が自動追従するため、ここでは Ghostty を直接
-- 触らない (= 疎結合: 時刻トリガー層は OS appearance だけ動かす)。
--
-- 必要権限: hs.osascript.applescript で System Events を呼ぶには
-- Automation 権限 (System Settings → Privacy & Security → Automation
-- → Hammerspoon → System Events を ON) が必要。Accessibility とは別枠で、
-- 初回実行時に macOS のダイアログが出る。承認後は永続的に有効。
--
-- 動作:
--   1. 07:00 に Light、14:00 に Dark を hs.timer.doAt で 1 日周期で発火
--   2. cold start (Hammerspoon 起動 / hs.reload()) 時にも 1 度、現在時刻
--      に対する期待状態へ強制同期。「再ログイン後に時刻外れの状態で固まる」
--      事故を避ける (= 手動 override より時刻ルールを優先する設計判断)
--   3. timer はグローバル変数で保持。watcher と同様に GC で破棄されない
--      ようにするため

local APPEARANCE_LIGHT_HOUR = 7   -- 07:00 に Light へ
local APPEARANCE_DARK_HOUR = 14   -- 14:00 に Dark へ

-- 時刻ベース appearance 自動切替の machine-local OFF スイッチ。
-- このファイルが存在する間は時刻トリガー (timer / cold-start sync) を
-- 早期 return で無効化する。Ghostty font-size 連動 (= appearance 変更
-- 通知の購読) は別系統なので、手動で OS appearance を切り替えれば
-- font-size はそのまま追従する。
--
-- 運用:
--   touch ~/.hammerspoon/appearance-auto.disabled   # OFF
--   rm    ~/.hammerspoon/appearance-auto.disabled   # ON に戻す
--   hs -c 'hs.reload()'                             # 即時反映
--
-- ~/.hammerspoon は homeshick で castle/hammerspoon/ への symlink な
-- ため flag ファイルは castle 配下に着地するが、.gitignore で
-- `hammerspoon/*.disabled` を無視しているので追跡されない。
local APPEARANCE_AUTO_DISABLE_FLAG = os.getenv("HOME")
    .. "/.hammerspoon/appearance-auto.disabled"

local function isAppearanceAutoDisabled()
    local f = io.open(APPEARANCE_AUTO_DISABLE_FLAG, "r")
    if f then f:close(); return true end
    return false
end

-- System Events 経由で OS の appearance を直接切替。Ventura 以降も有効な
-- 公式 AppleScript API。失敗時 (Automation 未承認等) は通知で自己申告する。
local function setInterfaceStyle(dark)
    local script = string.format([[
        tell application "System Events"
            tell appearance preferences
                set dark mode to %s
            end tell
        end tell
    ]], dark and "true" or "false")
    local ok, _, err = hs.osascript.applescript(script)
    if not ok then
        hs.notify.new({
            title = "Hammerspoon: appearance 切替に失敗",
            subTitle = "Automation 権限を確認してください",
            informativeText = "System Settings → Privacy & Security → Automation → Hammerspoon → System Events を ON にしてください",
            autoWithdraw = false,
        }):send()
    end
end

-- 現在時刻が "Dark の時間帯" かを返す。
-- LIGHT_HOUR <= h < DARK_HOUR を Light、それ以外を Dark とする
-- (= 本設定だと 07:00–13:59 が Light、14:00–06:59 が Dark)
local function shouldBeDarkNow()
    local h = tonumber(os.date("%H"))
    return not (h >= APPEARANCE_LIGHT_HOUR and h < APPEARANCE_DARK_HOUR)
end

-- 現在の OS appearance が期待値と違う場合のみ切替を発火。
-- 既に正しい状態なら notification を発生させず、Ghostty 再 reload も避ける。
-- flag file 存在時は cold-start 同期を skip し、現在の OS appearance を尊重する
-- (= ユーザーが手動で固定した状態を勝手に上書きしない)。状態が分かりにくいので
-- 短時間 alert で OFF 中であることを自己申告する。
local function applyExpectedAppearance()
    if isAppearanceAutoDisabled() then
        hs.alert.show(
            "⏸ appearance auto-switch is OFF\n"
                .. "(rm ~/.hammerspoon/appearance-auto.disabled to re-enable)",
            4
        )
        return
    end
    local wantDark = shouldBeDarkNow()
    local currentDark = currentInterfaceStyle() == "Dark"
    if wantDark ~= currentDark then
        setInterfaceStyle(wantDark)
    end
end

appearanceLightTimer = hs.timer.doAt(
    string.format("%02d:00", APPEARANCE_LIGHT_HOUR),
    "1d",
    function()
        if isAppearanceAutoDisabled() then return end
        setInterfaceStyle(false)
    end
)
appearanceDarkTimer = hs.timer.doAt(
    string.format("%02d:00", APPEARANCE_DARK_HOUR),
    "1d",
    function()
        if isAppearanceAutoDisabled() then return end
        setInterfaceStyle(true)
    end
)

-- cold start で現在時刻に対する期待状態へ同期。Ghostty 側 sync は
-- 切替に伴う notification 経由で自動的に再発火する。
applyExpectedAppearance()
